### ISSUE TITLE
Does this program support function code?

### ISSUE THREAD

**Issue by terencechuen** [epsilonrt/mbpoll#15]
In my environment, need to use function code, would you like to support it?

**Comment by epsilonrt** [comment]
This page is intended to report mbpoll bugs or to propose new features. your question seems to indicate that you have a very vague idea of how MODBUS works. I advise you to head to one of the multiple forums dedicated to MODBUS.

**Comment by 0xStuart** [comment]
Seems like a reasonable request.  mbpoll is sending out function code 3, and the slave I am reading is expecting 4.  There doesn't appear to be a way of changing it.

**Comment by terencechuen** [comment]
@0xStuart You may try "-t 4" parameter, the default is 16-bit output (holding) register data type.

![image](https://github.com/epsilonrt/mbpoll/assets/18247300/3103df30-1205-4f89-a64e-976ecb0fe5d6)
