### ISSUE TITLE
exit code not set properly

### ISSUE THREAD

**Issue by gerritkuehn** [epsilonrt/mbpoll#17]
It looks like I do not get proper exit codes on (any) failures (I tried so far):

pem scripts # ../bin/mbpoll -1 -t1 -r 15 -c1 10.117.12.12
mbpoll 1.3-3 - FieldTalk(tm) Modbus(R) Master Simulator
Copyright (c) 2015 epsilonRT, All rights reserved.
This software is governed by the CeCILL license <http://www.cecill.info>

Protocol configuration: Modbus TCP
Slave configuration...: address = [1]
                        start reference = 15, count = 1
Communication.........: 10.117.12.12, port 502, t/o 1.00 s, poll rate 1000 ms
Data type.............: discrete input

-- Polling slave 1...
Read discrete input failed: Illegal function

pem scripts # echo $?
0

This should be different from 0.

**Comment by epsilonrt** [comment]
Thank you for your participation.
The Issue has been solved.
