### ISSUE TITLE
Compatible hardware for Raspberry

### ISSUE THREAD

**Issue by poune** [epsilonrt/mbpoll#20]
Hello,

Do you know wich hardware is compatible on Rapberry to access througth RS485 (Hat or not)?

Thank you !

**Comment by epsilonrt** [comment]
Mbpoll uses libmodbus, so serial link compatibility depends on libmodbus.
Personally, I used Maxim integrated circuits like the MAX3430 successfully, you can also use RS485 USB interfaces without any problem.
