### ISSUE TITLE
qmake not running in Raspberry pi

### ISSUE THREAD

**Issue by abhinavrawat27** [epsilonrt/mbpoll#21]
Hi

I have followed the instructions on installing it on Raspberry Pi Stretch. I have properly setup qmake like below:

find /usr -name qmake | grep qt4
/usr/lib/arm-linux-gnueabihf/qt4/bin/qmake
/usr/share/qt4/bin/qmake

alias qmake="/usr/lib/arm-linux-gnueabihf/qt4/bin/qmake"

qmake

But when I run qmake, it only gives me its help options and nothing else. If I execute command `make` after `qmake`, it says no target files specified. Please help

**Comment by epsilonrt** [comment]
mbpoll no longer uses qmake but cmake.
I advise you to follow the README file to perform the installation.
Good luck.
