### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by johnwmail** [epsilonrt/mbpoll#37]
Hi all, is there any mbpoll windows version free to download?
Thanks.

**Comment by epsilonrt** [comment]
Hi,
https://github.com/epsilonrt/mbpoll/releases
v0.2 only but work very well.

**Comment by johnwmail** [comment]
Great, and thanks.

**Comment by johnwmail** [comment]
But when I run it on windows 2016 (same command/parameters)
(It work well on linux)
 mbpoll -c 10  -B -t 4:float -1 192.168.0.100
mbpoll always show the error like this: 
![image](https://user-images.githubusercontent.com/1752235/81950270-506de080-9636-11ea-9572-06a8b04b5973.png)

**Comment by epsilonrt** [comment]
et si vous ajoutez `-m tcp` ?

**Comment by epsilonrt** [comment]
I opened a new issue #31
