### ISSUE TITLE
Missing parameter on Windows

### ISSUE THREAD

**Issue by epsilonrt** [epsilonrt/mbpoll#38]
But when I run it on windows 2016 (same command/parameters)
(It work well on linux)
 mbpoll -c 10  -B -t 4:float -1 192.168.0.100
mbpoll always show the error like this: 
![image](https://user-images.githubusercontent.com/1752235/81950270-506de080-9636-11ea-9572-06a8b04b5973.png)

_Originally posted by @johnwmail in https://github.com/epsilonrt/mbpoll/issues/37#issuecomment-628691245_

**Comment by johnwmail** [comment]
Hi epsilonrt, thanks for your help.
But after added -m tcp -p 502, still not work on windows

![image](https://user-images.githubusercontent.com/1752235/82002582-b6875180-9690-11ea-99ac-5fde114b8f4a.png)

Any idea, how to fix it?
Thanks.

**Comment by johnwmail** [comment]
Hi, only me/windows 2016 have this problem?

**Comment by epsilonrt** [comment]
Yes.
mbpoll 1 will no longer be updated, I will switch to mbpoll 2 with the integration of [libmodbuspp](https://github.com/epsilonrt/libmodbuspp).
I recommend that you recompile under Windows 16 from sources. You have to use cmake and the MS compiler.
Good luck.
