### ISSUE TITLE
error when polling slave address 255

### ISSUE THREAD

**Issue by whuang0705** [epsilonrt/mbpoll#62]
get following message when polling slave address 255, device is Renogy Wanderer 10A battery charger.

-- Polling slave 255...
mbpoll: modbus-rtu.c:110: _modbus_rtu_build_request_basis: Assertion `ctx->slave != -1' failed.
Aborted

Have tried on other Renogy Wanderer 30A battery charger which has slave address 1 and 255, works on 1 and got the same error on 255.  This device can be polled from either slave address 1 or 255 when using qmodmaster, https://sourceforge.net/projects/qmodmaster/,  under MS-windows 10

Any help/suggestion would be much appreciated.

Regards,
Wade H.

**Comment by epsilonrt** [comment]
Hi,
This message is a libmodbus error, not an mbpoll error.
Could you tell me if it works with addresses from 1 to 247?
If this is the case and the error is only displayed for addresses from 248 to 255, then you are not respecting the [MODBUS OSL specifications](https://modbus.org/docs/Modbus_over_serial_line_V1_02 .pdf), addresses 248 to 255 are reserved and therefore not allowed.
Regards.
