### ISSUE TITLE
Help with right settings

### ISSUE THREAD

**Issue by mStirner** [epsilonrt/mbpoll#68]
First: thanks for the great work. :)

To my issue: I have trouble reading values from my smart meter.
Im not sure if the settings/arguments are correct.

From the docs:
![grafik](https://github.com/epsilonrt/mbpoll/assets/5003424/5b9c86c7-1b85-4402-9919-a93af4483e85)

so to read the address 30001, i was using the following command:
`mbpoll -m=tcp -a 1 -t 3:float -v -c 1 -1 -r 30001  smart-meter.lan`

But i get not the voltage, it just returns `0`.

```
marc@stirner:~$ mbpoll -a 1 -t 3:float -v -c 1 -1 -r 30001  smart-meter.lan
debug enabled
Set number of values=1
Set start reference=30001
Set device=smart-meter.lan
mbpoll 1.4-12 - FieldTalk(tm) Modbus(R) Master Simulator
Copyright © 2015-2019 Pascal JEAN, https://github.com/epsilonrt/mbpoll
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type 'mbpoll -w' for details.

Connecting to [smart-meter.lan]:502
Set response timeout to 1 sec, 0 us
Protocol configuration: Modbus TCP
Slave configuration...: address = [1]
                        start reference = 30001, count = 1
Communication.........: smart-meter.lan, port 502, t/o 1.00 s, poll rate 1000 ms
Data type.............: 32-bit float (little endian), input register table

-- Polling slave 1...
[00][01][00][00][00][06][01][04][75][30][00][02]
Waiting for a confirmation...
<00><01><00><00><00><07><01><04><04><00><00><00><00>
[30001]: 	0
```

Is the command i use correct?

Thanks in advance.

**Comment by mStirner** [comment]
This is what should be send to the modbus device: `01 04 00 00 00 02 71 cb`.
But it seems i cant set the register/address to `0`.

When i use `mbpoll -m rtu -b 9600 -P none -d 8 -t 3:float -1 -r 0 -v /dev/ttyUSB0`, i get:
```
root@smart-meter:/opt/smart-meter# mbpoll -m rtu -b 9600 -P none -d 8 -t 3:float -1 -r 0 -v /dev/ttyUSB0 
debug enabled
mbpoll: start reference out of range (0) ! Try -h for help.

```

**Comment by git-developer** [comment]
The reference `-r` is 1-based by default. Value 0 is reserved for special meaning "broadcast" (currently unsupported by mbpoll / #39).

Maybe it helps when you add the argument `-0` to change this behavior.

**Comment by mStirner** [comment]
I have currently no access to the device.
But how can i read the L1 - N Voltage (addr 30001) when i cant use 0 as value?

> The reference `-r` is 1-based by default. Value 0 is reserved for special meaning "broadcast" (currently unsupported by mbpoll / #39).
> 
> Maybe it helps when you add the argument `-0` to change this behavior.

What also confuses me is, that i do not use the "Register address" from the docs above, but the "Modbus protocol start address"

**Comment by epsilonrt** [comment]
Take the time to carefully read the MODBUS APPLICATION PROTOCOL SPECIFICATION V1.1b3 document, in particular paragraph 4.4 MODBUS Addressing model
the -r option designates the address of a REGISTER and not the address of the slave. You can use the numbering based on 0 by passing the -0 option (which does not concern the -a option but only the -r option).

**Comment by git-developer** [comment]
> But how can i read the L1 - N Voltage (addr 30001) when i cant use 0 as value?

You wrote:
```shell
root@smart-meter:/opt/smart-meter# mbpoll -m rtu -b 9600 -P none -d 8 -t 3:float -1 -r 2 -v /dev/ttyUSB0 
...
[01][04][00][01][00][02][20][0B]
```
The hex output means:
- `[01]`: talk to first slave
- `[04]`: function code to read an input register
- `[00][01]`: start reading at the second register
- `[00][02]`: read two bytes
- `[20][0B]`: checksum

So you just have to replace `-r 2` by `-r 1` to read the first register (with hex address `[00][00]` / register address 30001):
```
# mbpoll -m rtu -b 9600 -P none -d 8 -t 3:float -1 -r 1 -v /dev/ttyUSB0 
...
[01][04][00][00][00][02][71][CB]
```
