### ISSUE TITLE
mbpoll built on OpenWRT

### ISSUE THREAD

**Issue by richi-chen** [epsilonrt/mbpoll#7]
Hi epsilonrt,

I want to build mbpoll in OpenWRT system running on MTK MT7688 which is MIPS CPU.
How do you think it should be built to an OpenWRT package for mbpoll?

Thanks!

**Comment by epsilonrt** [comment]
Hi,
I just merged the master branch on branch r1.2.
The project now uses cmake, if you are the instructions to compile the file REAME.md you should be able to compile without problem on your system.
Regards

**Comment by richi-chen** [comment]
Hi epsilonrt,

I have built mbpoll in OpenWRT and work well, thank you!
