### ISSUE TITLE
Function codes

### ISSUE THREAD

**Issue by paula75** [epsilonrt/mbpoll#9]
Thanks for the project!
It's very useful and easy to use. I have a question, the general options to read the values in this tool is not concordant with the function codes in classical Modbus function codes, is it?

In Modbus the function code 3 is to read holding register and 4 is to read input register, instead in the implementation of this tool the opcion -t 3 is for read input register data types and 4 is to read output holding register, that is, they are the other way around.

the same for -t 0/1 maybe would be better to use 1, 2, 3, 4 classic modes for modbus function codes

**Comment by epsilonrt** [comment]
Hello,
Yes, it's voluntary. As indicated in the README file:
_"Although the syntax of these options is very close modpoll proconX program, it is a completely independent project."_
It's the choice I made.
Best regards
